=begin
#Yext API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Yext::HealthcareFacilityWriteAllOfCalendars
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Yext::HealthcareFacilityWriteAllOfCalendars do
  let(:instance) { Yext::HealthcareFacilityWriteAllOfCalendars.new }

  describe 'test an instance of HealthcareFacilityWriteAllOfCalendars' do
    it 'should create an instance of HealthcareFacilityWriteAllOfCalendars' do
      expect(instance).to be_instance_of(Yext::HealthcareFacilityWriteAllOfCalendars)
    end
  end
  describe 'test attribute "ids"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "label"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
