=begin
#Yext API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Yext::InlineResponse200ResponseFacebookProfilePhoto
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Yext::InlineResponse200ResponseFacebookProfilePhoto do
  let(:instance) { Yext::InlineResponse200ResponseFacebookProfilePhoto.new }

  describe 'test an instance of InlineResponse200ResponseFacebookProfilePhoto' do
    it 'should create an instance of InlineResponse200ResponseFacebookProfilePhoto' do
      expect(instance).to be_instance_of(Yext::InlineResponse200ResponseFacebookProfilePhoto)
    end
  end
  describe 'test attribute "alternate_text"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
