=begin
#Yext API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Yext::JobWriteAllOfLocation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Yext::JobWriteAllOfLocation do
  let(:instance) { Yext::JobWriteAllOfLocation.new }

  describe 'test an instance of JobWriteAllOfLocation' do
    it 'should create an instance of JobWriteAllOfLocation' do
      expect(instance).to be_instance_of(Yext::JobWriteAllOfLocation)
    end
  end
  describe 'test attribute "existing_location"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "external_location"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
