=begin
#Yext API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Yext::ListEntities200ResponseResponseEntitiesInnerOnlineServiceHoursMonday
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Yext::ListEntities200ResponseResponseEntitiesInnerOnlineServiceHoursMonday do
  let(:instance) { Yext::ListEntities200ResponseResponseEntitiesInnerOnlineServiceHoursMonday.new }

  describe 'test an instance of ListEntities200ResponseResponseEntitiesInnerOnlineServiceHoursMonday' do
    it 'should create an instance of ListEntities200ResponseResponseEntitiesInnerOnlineServiceHoursMonday' do
      expect(instance).to be_instance_of(Yext::ListEntities200ResponseResponseEntitiesInnerOnlineServiceHoursMonday)
    end
  end
  describe 'test attribute "is_closed"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "open_intervals"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
