=begin
#Yext API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Yext::ListEntities200ResponseResponseEntitiesInnerServiceAreaPlacesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Yext::ListEntities200ResponseResponseEntitiesInnerServiceAreaPlacesInner do
  let(:instance) { Yext::ListEntities200ResponseResponseEntitiesInnerServiceAreaPlacesInner.new }

  describe 'test an instance of ListEntities200ResponseResponseEntitiesInnerServiceAreaPlacesInner' do
    it 'should create an instance of ListEntities200ResponseResponseEntitiesInnerServiceAreaPlacesInner' do
      expect(instance).to be_instance_of(Yext::ListEntities200ResponseResponseEntitiesInnerServiceAreaPlacesInner)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["POSTAL_CODE", "REGION", "COUNTY", "CITY", "SUBLOCALITY"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

end
