=begin
#Yext Admin API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Yext::NewLocationAddRequestHealthcareProfessional
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Yext::NewLocationAddRequestHealthcareProfessional do
  let(:instance) { Yext::NewLocationAddRequestHealthcareProfessional.new }

  describe 'test an instance of NewLocationAddRequestHealthcareProfessional' do
    it 'should create an instance of NewLocationAddRequestHealthcareProfessional' do
      expect(instance).to be_instance_of(Yext::NewLocationAddRequestHealthcareProfessional)
    end
  end
  describe 'test attribute "new_entity_data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
