=begin
#Yext Admin API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Yext::ProcessReviewAddRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Yext::ProcessReviewAddRequest do
  let(:instance) { Yext::ProcessReviewAddRequest.new }

  describe 'test an instance of ProcessReviewAddRequest' do
    it 'should create an instance of ProcessReviewAddRequest' do
      expect(instance).to be_instance_of(Yext::ProcessReviewAddRequest)
    end
  end
  describe 'test attribute "add_request_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
